title: Plant Picture Library
email: niklas.conen@student.kit.edu
description: >-
  Plant Picture Library
baseurl: /plant-picture-library
url: "https://nordegraf.github.io/"
imageurl: "https://nordegraf.github.io/"
author: Niklas Conen
year: 2023

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

feed:
  excerpt_only: true
  collections:
    - plants

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  trail:
    before: 2
    after: 2

exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:day/:title.html

collections:
  pages:
    output: true
    permalink: /:name

  plants:
    output: false
    permalink: /:collection/:name

plant_attributes:
  # attributes must be unique!
  # attributes are ordered by the order of appearance in the file
  # place is defined by country => location
  place:
    - country
    - city
    - location
  #taxonomy:
  #  - group
  #  - family
  #  - genus
  #  - species
